### ISSUE TITLE
Loading extension not possible in QGIS 3.22

### ISSUE THREAD

**Issue by veroniqueC** [NINAnor/GarminCustomMaps#26]
Hy,

I used QGIS 3.22 . I have an error message when i want to load this extension
TypeError 'QVariant' object is not subscriptable
![image](https://user-images.githubusercontent.com/13468107/187448878-f0fca905-9ce2-4af7-853a-a7f47d93e740.png)

Thanks

PS: it seems to come from my test profil

**Comment by esan0** [comment]
Hi there,

Could you try upgrading to the latest QGIS to see if that fixes the issue?

Also, I see that you commented on another issue, relating the zoom factor -- so are you able to load the plugin now, but you are getting a different error?

Please clarify so that we can either help resolve or close this issue.

Thanks,
Egor

**Comment by veroniqueC** [comment]
Thanks for your answer.

I used this expression in the QGIS shortcut --profiles-path "C:\Users\xxxxx\AppData\Roaming\QGIS\QGIS322" to change the profil repertory, and it seems to be that which induced the error. On an installation without this expression, it seems to be OK

**Comment by esan0** [comment]
Great! I will close this issue then.
Thanks,
Egor
